spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/youtube-crawler
    username: postgres
    password: postgres
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          time_zone: Europe/Warsaw

daysLimit: 30
